# -*- coding: utf-8 -*-
"""program6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Syz-AVx2J1nTtYSz7OLi2tNGDYu54vjU
"""

import matplotlib.pyplot as plt
x = [1, 2, 3, 4, 5]
y = [2, 3, 5, 7, 11]
plt.plot(x, y, marker='o')# Create line plot
plt.title('Line Plot')
plt.xlabel('X-axis')
plt.ylabel('Y-axis')
plt.show()